//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 22/8/2018 10:03:31
namespace Aparte.ApiClient.Aparte.Models
{
    /// <summary>
    /// There are no comments for TenantSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("TenantSingle")]
    public partial class TenantSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Tenant>
    {
        /// <summary>
        /// Initialize a new TenantSingle object.
        /// </summary>
        public TenantSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new TenantSingle object.
        /// </summary>
        public TenantSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new TenantSingle object.
        /// </summary>
        public TenantSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Tenant> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Tenant in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PK
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PK")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Tenant")]
    public partial class Tenant : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Tenant object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="pK">Initial value of PK.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Tenant CreateTenant(string name, long pK)
        {
            Tenant tenant = new Tenant();
            tenant.Name = name;
            tenant.PK = pK;
            return tenant;
        }
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Code")]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this._Code = value;
                this.OnCodeChanged();
                this.OnPropertyChanged("Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property PK in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PK")]
        public long PK
        {
            get
            {
                return this._PK;
            }
            set
            {
                this.OnPKChanging(value);
                this._PK = value;
                this.OnPKChanged();
                this.OnPropertyChanged("PK");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private long _PK;
        partial void OnPKChanging(long value);
        partial void OnPKChanged();
        /// <summary>
        /// There are no comments for Property GlobalID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("GlobalID")]
        public string GlobalID
        {
            get
            {
                return this._GlobalID;
            }
            set
            {
                this.OnGlobalIDChanging(value);
                this._GlobalID = value;
                this.OnGlobalIDChanged();
                this.OnPropertyChanged("GlobalID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _GlobalID;
        partial void OnGlobalIDChanging(string value);
        partial void OnGlobalIDChanged();
        /// <summary>
        /// There are no comments for Property Inserted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Inserted")]
        public global::System.Nullable<global::System.DateTimeOffset> Inserted
        {
            get
            {
                return this._Inserted;
            }
            set
            {
                this.OnInsertedChanging(value);
                this._Inserted = value;
                this.OnInsertedChanged();
                this.OnPropertyChanged("Inserted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Inserted;
        partial void OnInsertedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnInsertedChanged();
        /// <summary>
        /// There are no comments for Property LastModified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastModified")]
        public global::System.Nullable<global::System.DateTimeOffset> LastModified
        {
            get
            {
                return this._LastModified;
            }
            set
            {
                this.OnLastModifiedChanging(value);
                this._LastModified = value;
                this.OnLastModifiedChanged();
                this.OnPropertyChanged("LastModified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _LastModified;
        partial void OnLastModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnLastModifiedChanged();
        /// <summary>
        /// There are no comments for Property Deleted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Deleted")]
        public global::System.Nullable<global::System.DateTimeOffset> Deleted
        {
            get
            {
                return this._Deleted;
            }
            set
            {
                this.OnDeletedChanging(value);
                this._Deleted = value;
                this.OnDeletedChanged();
                this.OnPropertyChanged("Deleted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Deleted;
        partial void OnDeletedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDeletedChanged();
        /// <summary>
        /// There are no comments for Property Timestamp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Timestamp")]
        public byte[] Timestamp
        {
            get
            {
                return this._Timestamp;
            }
            set
            {
                this.OnTimestampChanging(value);
                this._Timestamp = value;
                this.OnTimestampChanged();
                this.OnPropertyChanged("Timestamp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private byte[] _Timestamp;
        partial void OnTimestampChanging(byte[] value);
        partial void OnTimestampChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for SystemUserSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("SystemUserSingle")]
    public partial class SystemUserSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<SystemUser>
    {
        /// <summary>
        /// Initialize a new SystemUserSingle object.
        /// </summary>
        public SystemUserSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new SystemUserSingle object.
        /// </summary>
        public SystemUserSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new SystemUserSingle object.
        /// </summary>
        public SystemUserSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<SystemUser> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for SystemUser in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PK
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PK")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("SystemUser")]
    public partial class SystemUser : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SystemUser object.
        /// </summary>
        /// <param name="isGlobalAdmin">Initial value of IsGlobalAdmin.</param>
        /// <param name="pK">Initial value of PK.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static SystemUser CreateSystemUser(bool isGlobalAdmin, long pK)
        {
            SystemUser systemUser = new SystemUser();
            systemUser.IsGlobalAdmin = isGlobalAdmin;
            systemUser.PK = pK;
            return systemUser;
        }
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Code")]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this._Code = value;
                this.OnCodeChanged();
                this.OnPropertyChanged("Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property PasswordKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PasswordKey")]
        public byte[] PasswordKey
        {
            get
            {
                return this._PasswordKey;
            }
            set
            {
                this.OnPasswordKeyChanging(value);
                this._PasswordKey = value;
                this.OnPasswordKeyChanged();
                this.OnPropertyChanged("PasswordKey");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private byte[] _PasswordKey;
        partial void OnPasswordKeyChanging(byte[] value);
        partial void OnPasswordKeyChanged();
        /// <summary>
        /// There are no comments for Property PasswordSalt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PasswordSalt")]
        public byte[] PasswordSalt
        {
            get
            {
                return this._PasswordSalt;
            }
            set
            {
                this.OnPasswordSaltChanging(value);
                this._PasswordSalt = value;
                this.OnPasswordSaltChanged();
                this.OnPropertyChanged("PasswordSalt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private byte[] _PasswordSalt;
        partial void OnPasswordSaltChanging(byte[] value);
        partial void OnPasswordSaltChanged();
        /// <summary>
        /// There are no comments for Property IsGlobalAdmin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IsGlobalAdmin")]
        public bool IsGlobalAdmin
        {
            get
            {
                return this._IsGlobalAdmin;
            }
            set
            {
                this.OnIsGlobalAdminChanging(value);
                this._IsGlobalAdmin = value;
                this.OnIsGlobalAdminChanged();
                this.OnPropertyChanged("IsGlobalAdmin");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private bool _IsGlobalAdmin;
        partial void OnIsGlobalAdminChanging(bool value);
        partial void OnIsGlobalAdminChanged();
        /// <summary>
        /// There are no comments for Property PK in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PK")]
        public long PK
        {
            get
            {
                return this._PK;
            }
            set
            {
                this.OnPKChanging(value);
                this._PK = value;
                this.OnPKChanged();
                this.OnPropertyChanged("PK");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private long _PK;
        partial void OnPKChanging(long value);
        partial void OnPKChanged();
        /// <summary>
        /// There are no comments for Property GlobalID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("GlobalID")]
        public string GlobalID
        {
            get
            {
                return this._GlobalID;
            }
            set
            {
                this.OnGlobalIDChanging(value);
                this._GlobalID = value;
                this.OnGlobalIDChanged();
                this.OnPropertyChanged("GlobalID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _GlobalID;
        partial void OnGlobalIDChanging(string value);
        partial void OnGlobalIDChanged();
        /// <summary>
        /// There are no comments for Property Inserted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Inserted")]
        public global::System.Nullable<global::System.DateTimeOffset> Inserted
        {
            get
            {
                return this._Inserted;
            }
            set
            {
                this.OnInsertedChanging(value);
                this._Inserted = value;
                this.OnInsertedChanged();
                this.OnPropertyChanged("Inserted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Inserted;
        partial void OnInsertedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnInsertedChanged();
        /// <summary>
        /// There are no comments for Property LastModified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastModified")]
        public global::System.Nullable<global::System.DateTimeOffset> LastModified
        {
            get
            {
                return this._LastModified;
            }
            set
            {
                this.OnLastModifiedChanging(value);
                this._LastModified = value;
                this.OnLastModifiedChanged();
                this.OnPropertyChanged("LastModified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _LastModified;
        partial void OnLastModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnLastModifiedChanged();
        /// <summary>
        /// There are no comments for Property Deleted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Deleted")]
        public global::System.Nullable<global::System.DateTimeOffset> Deleted
        {
            get
            {
                return this._Deleted;
            }
            set
            {
                this.OnDeletedChanging(value);
                this._Deleted = value;
                this.OnDeletedChanged();
                this.OnPropertyChanged("Deleted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Deleted;
        partial void OnDeletedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDeletedChanged();
        /// <summary>
        /// There are no comments for Property Timestamp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Timestamp")]
        public byte[] Timestamp
        {
            get
            {
                return this._Timestamp;
            }
            set
            {
                this.OnTimestampChanging(value);
                this._Timestamp = value;
                this.OnTimestampChanged();
                this.OnPropertyChanged("Timestamp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private byte[] _Timestamp;
        partial void OnTimestampChanging(byte[] value);
        partial void OnTimestampChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for TenantUserSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("TenantUserSingle")]
    public partial class TenantUserSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<TenantUser>
    {
        /// <summary>
        /// Initialize a new TenantUserSingle object.
        /// </summary>
        public TenantUserSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new TenantUserSingle object.
        /// </summary>
        public TenantUserSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new TenantUserSingle object.
        /// </summary>
        public TenantUserSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<TenantUser> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for TenantUser in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PK
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PK")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("TenantUser")]
    public partial class TenantUser : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new TenantUser object.
        /// </summary>
        /// <param name="registered">Initial value of Registered.</param>
        /// <param name="pK">Initial value of PK.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static TenantUser CreateTenantUser(global::System.DateTimeOffset registered, long pK)
        {
            TenantUser tenantUser = new TenantUser();
            tenantUser.Registered = registered;
            tenantUser.PK = pK;
            return tenantUser;
        }
        /// <summary>
        /// There are no comments for Property FKTenant in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("FKTenant")]
        public global::System.Nullable<long> FKTenant
        {
            get
            {
                return this._FKTenant;
            }
            set
            {
                this.OnFKTenantChanging(value);
                this._FKTenant = value;
                this.OnFKTenantChanged();
                this.OnPropertyChanged("FKTenant");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<long> _FKTenant;
        partial void OnFKTenantChanging(global::System.Nullable<long> value);
        partial void OnFKTenantChanged();
        /// <summary>
        /// There are no comments for Property FKSystemUser in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("FKSystemUser")]
        public global::System.Nullable<long> FKSystemUser
        {
            get
            {
                return this._FKSystemUser;
            }
            set
            {
                this.OnFKSystemUserChanging(value);
                this._FKSystemUser = value;
                this.OnFKSystemUserChanged();
                this.OnPropertyChanged("FKSystemUser");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<long> _FKSystemUser;
        partial void OnFKSystemUserChanging(global::System.Nullable<long> value);
        partial void OnFKSystemUserChanged();
        /// <summary>
        /// There are no comments for Property FKParty in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("FKParty")]
        public global::System.Nullable<long> FKParty
        {
            get
            {
                return this._FKParty;
            }
            set
            {
                this.OnFKPartyChanging(value);
                this._FKParty = value;
                this.OnFKPartyChanged();
                this.OnPropertyChanged("FKParty");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<long> _FKParty;
        partial void OnFKPartyChanging(global::System.Nullable<long> value);
        partial void OnFKPartyChanged();
        /// <summary>
        /// There are no comments for Property Registered in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Registered")]
        public global::System.DateTimeOffset Registered
        {
            get
            {
                return this._Registered;
            }
            set
            {
                this.OnRegisteredChanging(value);
                this._Registered = value;
                this.OnRegisteredChanged();
                this.OnPropertyChanged("Registered");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _Registered;
        partial void OnRegisteredChanging(global::System.DateTimeOffset value);
        partial void OnRegisteredChanged();
        /// <summary>
        /// There are no comments for Property PK in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PK")]
        public long PK
        {
            get
            {
                return this._PK;
            }
            set
            {
                this.OnPKChanging(value);
                this._PK = value;
                this.OnPKChanged();
                this.OnPropertyChanged("PK");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private long _PK;
        partial void OnPKChanging(long value);
        partial void OnPKChanged();
        /// <summary>
        /// There are no comments for Property GlobalID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("GlobalID")]
        public string GlobalID
        {
            get
            {
                return this._GlobalID;
            }
            set
            {
                this.OnGlobalIDChanging(value);
                this._GlobalID = value;
                this.OnGlobalIDChanged();
                this.OnPropertyChanged("GlobalID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _GlobalID;
        partial void OnGlobalIDChanging(string value);
        partial void OnGlobalIDChanged();
        /// <summary>
        /// There are no comments for Property Inserted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Inserted")]
        public global::System.Nullable<global::System.DateTimeOffset> Inserted
        {
            get
            {
                return this._Inserted;
            }
            set
            {
                this.OnInsertedChanging(value);
                this._Inserted = value;
                this.OnInsertedChanged();
                this.OnPropertyChanged("Inserted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Inserted;
        partial void OnInsertedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnInsertedChanged();
        /// <summary>
        /// There are no comments for Property LastModified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastModified")]
        public global::System.Nullable<global::System.DateTimeOffset> LastModified
        {
            get
            {
                return this._LastModified;
            }
            set
            {
                this.OnLastModifiedChanging(value);
                this._LastModified = value;
                this.OnLastModifiedChanged();
                this.OnPropertyChanged("LastModified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _LastModified;
        partial void OnLastModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnLastModifiedChanged();
        /// <summary>
        /// There are no comments for Property Deleted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Deleted")]
        public global::System.Nullable<global::System.DateTimeOffset> Deleted
        {
            get
            {
                return this._Deleted;
            }
            set
            {
                this.OnDeletedChanging(value);
                this._Deleted = value;
                this.OnDeletedChanged();
                this.OnPropertyChanged("Deleted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Deleted;
        partial void OnDeletedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDeletedChanged();
        /// <summary>
        /// There are no comments for Property Timestamp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Timestamp")]
        public byte[] Timestamp
        {
            get
            {
                return this._Timestamp;
            }
            set
            {
                this.OnTimestampChanging(value);
                this._Timestamp = value;
                this.OnTimestampChanged();
                this.OnPropertyChanged("Timestamp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private byte[] _Timestamp;
        partial void OnTimestampChanging(byte[] value);
        partial void OnTimestampChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for XAttributeSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("xAttributeSingle")]
    public partial class XAttributeSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<XAttribute>
    {
        /// <summary>
        /// Initialize a new XAttributeSingle object.
        /// </summary>
        public XAttributeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new XAttributeSingle object.
        /// </summary>
        public XAttributeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new XAttributeSingle object.
        /// </summary>
        public XAttributeSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<XAttribute> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for XAttribute in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PK
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PK")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("xAttribute")]
    public partial class XAttribute : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new XAttribute object.
        /// </summary>
        /// <param name="rules">Initial value of Rules.</param>
        /// <param name="pK">Initial value of PK.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static XAttribute CreateXAttribute(global::Aparte.ApiClient.Aparte.MasterData.AttributeRule rules, long pK)
        {
            XAttribute xAttribute = new XAttribute();
            xAttribute.Rules = rules;
            xAttribute.PK = pK;
            return xAttribute;
        }
        /// <summary>
        /// There are no comments for Property Rules in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Rules")]
        public global::Aparte.ApiClient.Aparte.MasterData.AttributeRule Rules
        {
            get
            {
                return this._Rules;
            }
            set
            {
                this.OnRulesChanging(value);
                this._Rules = value;
                this.OnRulesChanged();
                this.OnPropertyChanged("Rules");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Aparte.ApiClient.Aparte.MasterData.AttributeRule _Rules;
        partial void OnRulesChanging(global::Aparte.ApiClient.Aparte.MasterData.AttributeRule value);
        partial void OnRulesChanged();
        /// <summary>
        /// There are no comments for Property PK in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PK")]
        public long PK
        {
            get
            {
                return this._PK;
            }
            set
            {
                this.OnPKChanging(value);
                this._PK = value;
                this.OnPKChanged();
                this.OnPropertyChanged("PK");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private long _PK;
        partial void OnPKChanging(long value);
        partial void OnPKChanged();
        /// <summary>
        /// There are no comments for Property GlobalID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("GlobalID")]
        public string GlobalID
        {
            get
            {
                return this._GlobalID;
            }
            set
            {
                this.OnGlobalIDChanging(value);
                this._GlobalID = value;
                this.OnGlobalIDChanged();
                this.OnPropertyChanged("GlobalID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _GlobalID;
        partial void OnGlobalIDChanging(string value);
        partial void OnGlobalIDChanged();
        /// <summary>
        /// There are no comments for Property Inserted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Inserted")]
        public global::System.Nullable<global::System.DateTimeOffset> Inserted
        {
            get
            {
                return this._Inserted;
            }
            set
            {
                this.OnInsertedChanging(value);
                this._Inserted = value;
                this.OnInsertedChanged();
                this.OnPropertyChanged("Inserted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Inserted;
        partial void OnInsertedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnInsertedChanged();
        /// <summary>
        /// There are no comments for Property LastModified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastModified")]
        public global::System.Nullable<global::System.DateTimeOffset> LastModified
        {
            get
            {
                return this._LastModified;
            }
            set
            {
                this.OnLastModifiedChanging(value);
                this._LastModified = value;
                this.OnLastModifiedChanged();
                this.OnPropertyChanged("LastModified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _LastModified;
        partial void OnLastModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnLastModifiedChanged();
        /// <summary>
        /// There are no comments for Property Deleted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Deleted")]
        public global::System.Nullable<global::System.DateTimeOffset> Deleted
        {
            get
            {
                return this._Deleted;
            }
            set
            {
                this.OnDeletedChanging(value);
                this._Deleted = value;
                this.OnDeletedChanged();
                this.OnPropertyChanged("Deleted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Deleted;
        partial void OnDeletedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDeletedChanged();
        /// <summary>
        /// There are no comments for Property Timestamp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Timestamp")]
        public byte[] Timestamp
        {
            get
            {
                return this._Timestamp;
            }
            set
            {
                this.OnTimestampChanging(value);
                this._Timestamp = value;
                this.OnTimestampChanged();
                this.OnPropertyChanged("Timestamp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private byte[] _Timestamp;
        partial void OnTimestampChanging(byte[] value);
        partial void OnTimestampChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Aparte.ApiClient.Aparte.Models.Tenant as global::Aparte.ApiClient.Aparte.Models.TenantSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Aparte.ApiClient.Aparte.Models.TenantSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Aparte.ApiClient.Aparte.Models.Tenant> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Aparte.ApiClient.Aparte.Models.TenantSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Aparte.ApiClient.Aparte.Models.Tenant as global::Aparte.ApiClient.Aparte.Models.TenantSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="pK">The value of pK</param>
        public static global::Aparte.ApiClient.Aparte.Models.TenantSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Aparte.ApiClient.Aparte.Models.Tenant> source,
            long pK)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "PK", pK }
            };
            return new global::Aparte.ApiClient.Aparte.Models.TenantSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Aparte.ApiClient.Aparte.Models.SystemUser as global::Aparte.ApiClient.Aparte.Models.SystemUserSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Aparte.ApiClient.Aparte.Models.SystemUserSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Aparte.ApiClient.Aparte.Models.SystemUser> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Aparte.ApiClient.Aparte.Models.SystemUserSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Aparte.ApiClient.Aparte.Models.SystemUser as global::Aparte.ApiClient.Aparte.Models.SystemUserSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="pK">The value of pK</param>
        public static global::Aparte.ApiClient.Aparte.Models.SystemUserSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Aparte.ApiClient.Aparte.Models.SystemUser> source,
            long pK)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "PK", pK }
            };
            return new global::Aparte.ApiClient.Aparte.Models.SystemUserSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Aparte.ApiClient.Aparte.Models.TenantUser as global::Aparte.ApiClient.Aparte.Models.TenantUserSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Aparte.ApiClient.Aparte.Models.TenantUserSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Aparte.ApiClient.Aparte.Models.TenantUser> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Aparte.ApiClient.Aparte.Models.TenantUserSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Aparte.ApiClient.Aparte.Models.TenantUser as global::Aparte.ApiClient.Aparte.Models.TenantUserSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="pK">The value of pK</param>
        public static global::Aparte.ApiClient.Aparte.Models.TenantUserSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Aparte.ApiClient.Aparte.Models.TenantUser> source,
            long pK)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "PK", pK }
            };
            return new global::Aparte.ApiClient.Aparte.Models.TenantUserSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Aparte.ApiClient.Aparte.Models.XAttribute as global::Aparte.ApiClient.Aparte.Models.XAttributeSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Aparte.ApiClient.Aparte.Models.XAttributeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Aparte.ApiClient.Aparte.Models.XAttribute> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Aparte.ApiClient.Aparte.Models.XAttributeSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Aparte.ApiClient.Aparte.Models.XAttribute as global::Aparte.ApiClient.Aparte.Models.XAttributeSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="pK">The value of pK</param>
        public static global::Aparte.ApiClient.Aparte.Models.XAttributeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Aparte.ApiClient.Aparte.Models.XAttribute> source,
            long pK)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "PK", pK }
            };
            return new global::Aparte.ApiClient.Aparte.Models.XAttributeSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace Aparte.ApiClient.Aparte.MasterData
{
    /// <summary>
    /// There are no comments for AttributeRule in the schema.
    /// </summary>
    [global::System.Flags]
    [global::Microsoft.OData.Client.OriginalNameAttribute("AttributeRule")]
    public enum AttributeRule : long
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("None")]
        None = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("IsUniqe")]
        IsUniqe = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("UsePreset")]
        UsePreset = 2
    }
}
namespace Aparte.ApiClient.ODataService
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Aparte.MasterData", "Aparte.ApiClient.Aparte.MasterData");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Aparte.Models", "Aparte.ApiClient.Aparte.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "ODataService", "Aparte.ApiClient.ODataService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("Aparte.ApiClient.Aparte.MasterData", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Aparte.MasterData.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Aparte.MasterData.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Aparte.ApiClient.Aparte.Models", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Aparte.Models.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Aparte.Models.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Aparte.ApiClient.ODataService", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("ODataService.", originalNameAttribute.OriginalName);
                }
                return string.Concat("ODataService.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Tenants in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Tenants")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Aparte.ApiClient.Aparte.Models.Tenant> Tenants
        {
            get
            {
                if ((this._Tenants == null))
                {
                    this._Tenants = base.CreateQuery<global::Aparte.ApiClient.Aparte.Models.Tenant>("Tenants");
                }
                return this._Tenants;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Aparte.ApiClient.Aparte.Models.Tenant> _Tenants;
        /// <summary>
        /// There are no comments for SystemUsers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SystemUsers")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Aparte.ApiClient.Aparte.Models.SystemUser> SystemUsers
        {
            get
            {
                if ((this._SystemUsers == null))
                {
                    this._SystemUsers = base.CreateQuery<global::Aparte.ApiClient.Aparte.Models.SystemUser>("SystemUsers");
                }
                return this._SystemUsers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Aparte.ApiClient.Aparte.Models.SystemUser> _SystemUsers;
        /// <summary>
        /// There are no comments for TenantUsers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TenantUsers")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Aparte.ApiClient.Aparte.Models.TenantUser> TenantUsers
        {
            get
            {
                if ((this._TenantUsers == null))
                {
                    this._TenantUsers = base.CreateQuery<global::Aparte.ApiClient.Aparte.Models.TenantUser>("TenantUsers");
                }
                return this._TenantUsers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Aparte.ApiClient.Aparte.Models.TenantUser> _TenantUsers;
        /// <summary>
        /// There are no comments for Attributes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Attributes")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Aparte.ApiClient.Aparte.Models.XAttribute> Attributes
        {
            get
            {
                if ((this._Attributes == null))
                {
                    this._Attributes = base.CreateQuery<global::Aparte.ApiClient.Aparte.Models.XAttribute>("Attributes");
                }
                return this._Attributes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Aparte.ApiClient.Aparte.Models.XAttribute> _Attributes;
        /// <summary>
        /// There are no comments for Tenants in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToTenants(global::Aparte.ApiClient.Aparte.Models.Tenant tenant)
        {
            base.AddObject("Tenants", tenant);
        }
        /// <summary>
        /// There are no comments for SystemUsers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToSystemUsers(global::Aparte.ApiClient.Aparte.Models.SystemUser systemUser)
        {
            base.AddObject("SystemUsers", systemUser);
        }
        /// <summary>
        /// There are no comments for TenantUsers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToTenantUsers(global::Aparte.ApiClient.Aparte.Models.TenantUser tenantUser)
        {
            base.AddObject("TenantUsers", tenantUser);
        }
        /// <summary>
        /// There are no comments for Attributes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToAttributes(global::Aparte.ApiClient.Aparte.Models.XAttribute xAttribute)
        {
            base.AddObject("Attributes", xAttribute);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""Aparte.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Tenant"">
        <Key>
          <PropertyRef Name=""PK"" />
        </Key>
        <Property Name=""Code"" Type=""Edm.String"" />
        <Property Name=""Name"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""PK"" Type=""Edm.Int64"" Nullable=""false"" />
        <Property Name=""GlobalID"" Type=""Edm.String"" />
        <Property Name=""Inserted"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""LastModified"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""Deleted"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""Timestamp"" Type=""Edm.Binary"" />
      </EntityType>
      <EntityType Name=""SystemUser"">
        <Key>
          <PropertyRef Name=""PK"" />
        </Key>
        <Property Name=""Code"" Type=""Edm.String"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""PasswordKey"" Type=""Edm.Binary"" />
        <Property Name=""PasswordSalt"" Type=""Edm.Binary"" />
        <Property Name=""IsGlobalAdmin"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""PK"" Type=""Edm.Int64"" Nullable=""false"" />
        <Property Name=""GlobalID"" Type=""Edm.String"" />
        <Property Name=""Inserted"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""LastModified"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""Deleted"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""Timestamp"" Type=""Edm.Binary"" />
      </EntityType>
      <EntityType Name=""TenantUser"">
        <Key>
          <PropertyRef Name=""PK"" />
        </Key>
        <Property Name=""FKTenant"" Type=""Edm.Int64"" />
        <Property Name=""FKSystemUser"" Type=""Edm.Int64"" />
        <Property Name=""FKParty"" Type=""Edm.Int64"" />
        <Property Name=""Registered"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""PK"" Type=""Edm.Int64"" Nullable=""false"" />
        <Property Name=""GlobalID"" Type=""Edm.String"" />
        <Property Name=""Inserted"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""LastModified"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""Deleted"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""Timestamp"" Type=""Edm.Binary"" />
      </EntityType>
      <EntityType Name=""xAttribute"">
        <Key>
          <PropertyRef Name=""PK"" />
        </Key>
        <Property Name=""Rules"" Type=""Aparte.MasterData.AttributeRule"" Nullable=""false"" />
        <Property Name=""PK"" Type=""Edm.Int64"" Nullable=""false"" />
        <Property Name=""GlobalID"" Type=""Edm.String"" />
        <Property Name=""Inserted"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""LastModified"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""Deleted"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""Timestamp"" Type=""Edm.Binary"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""Aparte.MasterData"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EnumType Name=""AttributeRule"" UnderlyingType=""Edm.Int64"" IsFlags=""true"">
        <Member Name=""None"" Value=""0"" />
        <Member Name=""IsUniqe"" Value=""1"" />
        <Member Name=""UsePreset"" Value=""2"" />
      </EnumType>
    </Schema>
    <Schema Namespace=""ODataService"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <Function Name=""GetAttributes"">
        <Parameter Name=""ValueRule"" Type=""Aparte.MasterData.AttributeRule"" Nullable=""false"" />
        <ReturnType Type=""Collection(Aparte.Models.xAttribute)"" />
      </Function>
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Tenants"" EntityType=""Aparte.Models.Tenant"">
          <Annotation Term=""Org.OData.Core.V1.OptimisticConcurrency"">
            <Collection>
              <PropertyPath>Timestamp</PropertyPath>
            </Collection>
          </Annotation>
        </EntitySet>
        <EntitySet Name=""SystemUsers"" EntityType=""Aparte.Models.SystemUser"">
          <Annotation Term=""Org.OData.Core.V1.OptimisticConcurrency"">
            <Collection>
              <PropertyPath>Timestamp</PropertyPath>
            </Collection>
          </Annotation>
        </EntitySet>
        <EntitySet Name=""TenantUsers"" EntityType=""Aparte.Models.TenantUser"">
          <Annotation Term=""Org.OData.Core.V1.OptimisticConcurrency"">
            <Collection>
              <PropertyPath>Timestamp</PropertyPath>
            </Collection>
          </Annotation>
        </EntitySet>
        <EntitySet Name=""Attributes"" EntityType=""Aparte.Models.xAttribute"">
          <Annotation Term=""Org.OData.Core.V1.OptimisticConcurrency"">
            <Collection>
              <PropertyPath>Timestamp</PropertyPath>
            </Collection>
          </Annotation>
        </EntitySet>
        <FunctionImport Name=""GetAttributes"" Function=""ODataService.GetAttributes"" EntitySet=""Attributes"" IncludeInServiceDocument=""true"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
        /// <summary>
        /// There are no comments for GetAttributes in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("GetAttributes")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Aparte.ApiClient.Aparte.Models.XAttribute> GetAttributes(global::Aparte.ApiClient.Aparte.MasterData.AttributeRule ValueRule)
        {
            return this.CreateFunctionQuery<global::Aparte.ApiClient.Aparte.Models.XAttribute>("", "GetAttributes", false, new global::Microsoft.OData.Client.UriOperationParameter("ValueRule", ValueRule));
        }
    }
}
